FROM golang:1.26.1-alpine AS builder
ENV GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOEXPERIMENT=greenteagc
WORKDIR /build
RUN apk add --no-cache git bash ca-certificates
COPY go.mod go.sum ./
RUN go env -w GOPROXY=https://goproxy.cn,direct GOSUMDB=off && go mod download
COPY . .
RUN go build -ldflags "-s -w" -o new-api .

FROM calciumion/new-api:latest
COPY --from=builder /build/new-api /new-api
